version: '3.8'

services:
  web:
    build: .
    container_name: mini_t1_app
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    env_file:
      - .env
    networks:
      - mini_t1_network

networks:
  mini_t1_network:
    driver: bridge