"""Add is_finished to Contest

Revision ID: 29be76f52d74
Revises: f85ea3f9931a
Create Date: 2026-04-12 10:33:07.528294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29be76f52d74'
down_revision = 'f85ea3f9931a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_finished', sa.Boolean(), nullable=False, server_default='false'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contests', schema=None) as batch_op:
        batch_op.drop_column('is_finished')

    # ### end Alembic commands ###