"""add access_key to contest

Revision ID: a91f2fe56f53
Revises: 29be76f52d74
Create Date: 2026-04-23 08:26:19.127289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a91f2fe56f53'
down_revision = '29be76f52d74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('access_key', sa.String(length=64), nullable=True))
        batch_op.create_unique_constraint(None, ['access_key'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contests', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('access_key')

    # ### end Alembic commands ###