# Этап 1: Сборка Angular
FROM node:22-alpine as build
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build -- --configuration production

# Этап 2: Раздача статики через Nginx
FROM nginx:alpine
# Копируем кастомный конфиг Nginx, чтобы слушать на 4200 порту (как ожидает основной прокси)
COPY nginx-custom.conf /etc/nginx/conf.d/default.conf
# Копируем собранные файлы из первого этапа
COPY --from=build /app/dist/contest-app/browser /usr/share/nginx/html

EXPOSE 4200
CMD ["nginx", "-g", "daemon off;"]
